# Generated by Django 2.2.5 on 2019-10-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name_kana',
            field=models.CharField(blank=True, max_length=30, verbose_name='名(カナ)'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_kana',
            field=models.CharField(blank=True, max_length=150, verbose_name='姓(カナ)'),
        ),
    ]
