# Generated by Django 2.2.5 on 2019-12-09 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='adress_city',
            new_name='address_city',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='adress_detail',
            new_name='address_detail',
        ),
    ]
