# Generated by Django 2.2.5 on 2019-12-11 14:27

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191209_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='member_code',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='member_number',
            field=models.CharField(blank=True, default=users.models.create_member_number, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', '男性'), ('F', '女性'), ('O', 'その他')], max_length=10, verbose_name='性別'),
        ),
    ]
