# Generated by Django 2.2.5 on 2019-10-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191023_2234'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='adress_city',
            field=models.CharField(blank=True, max_length=40, verbose_name='市区町村番地'),
        ),
        migrations.AddField(
            model_name='user',
            name='adress_detail',
            field=models.CharField(blank=True, max_length=40, verbose_name='建物名・号室'),
        ),
        migrations.AddField(
            model_name='user',
            name='postal_code',
            field=models.CharField(blank=True, max_length=8, verbose_name='郵便番号'),
        ),
        migrations.AddField(
            model_name='user',
            name='prefecture',
            field=models.CharField(blank=True, max_length=10, verbose_name='都道府県'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
