# Generated by Django 2.2.5 on 2019-12-13 07:19

import core.models
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191211_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address_city',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='市区町村番地'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address_detail',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='建物名・号室'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='user',
            name='member_code',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='会員番号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='postal_code',
            field=core.models.JPPostalCodeModelField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='prefecture',
            field=core.models.JPPrefectureField(blank=True, max_length=2, null=True, verbose_name='都道府県'),
        ),
    ]
