# Generated by Django 2.2.5 on 2019-12-18 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_is_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_guest',
        ),
    ]
