# Generated by Django 2.2.5 on 2019-12-18 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20191218_1602'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guest',
        ),
    ]
