# Generated by Django 2.2.5 on 2019-12-18 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_guestemail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GuestEmail',
            new_name='Guest',
        ),
    ]
