# Generated by Django 2.2.5 on 2019-12-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20191225_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
