# Generated by Django 2.2.5 on 2019-12-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_guest_stripe_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='stripe_customer_id',
        ),
        migrations.AddField(
            model_name='guest',
            name='stripe_token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
