# Generated by Django 2.2.5 on 2019-12-27 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_guest_stripe_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='stripe_customer_id',
        ),
    ]
