# Generated by Django 2.2.5 on 2020-01-05 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_user_stripe_customer_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guest',
            options={'verbose_name': 'ゲスト', 'verbose_name_plural': 'ゲスト'},
        ),
    ]
