# Generated by Django 2.2.5 on 2020-01-25 09:07

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20200105_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='postal_code',
            field=core.models.JPPostalCodeModelField(blank=True, max_length=7, null=True, verbose_name='郵便番号'),
        ),
    ]
