# Generated by Django 2.2.5 on 2020-01-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20200125_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='active',
            field=models.BooleanField(default=True, verbose_name='活性化'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('', '--性別--'), ('M', '男性'), ('F', '女性'), ('O', 'その他')], max_length=10, verbose_name='性別'),
        ),
    ]
