# Generated by Django 2.2.5 on 2020-02-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20200127_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name_kana',
            field=models.CharField(blank=True, max_length=30, verbose_name='姓(カナ)'),
        ),
    ]
