# Generated by Django 2.2.5 on 2020-02-22 08:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20200221_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name_kana',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(code='invalid_username', message='テスト', regex='^[a-zA-Z]*$')], verbose_name='名(カナ)'),
        ),
    ]
