# Generated by Django 2.2.5 on 2020-02-22 09:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_auto_20200222_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(code='invalid-number', message='数字以外の文字で入力してください。', regex='[\\D]')], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(code='invalid', message='数字以外の文字で入力してください。', regex='[\\D]')], verbose_name='last name'),
        ),
    ]
