# Generated by Django 2.2.5 on 2019-12-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20191215_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='cart_id',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='product_id',
            new_name='product',
        ),
        migrations.AddField(
            model_name='cart',
            name='session_key',
            field=models.CharField(default=1, max_length=254, verbose_name='カートセッションキー'),
            preserve_default=False,
        ),
    ]
