# Generated by Django 2.2.5 on 2019-12-18 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0008_auto_20191218_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
