# Generated by Django 2.2.5 on 2020-01-05 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0014_cart_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='order',
        ),
    ]
