# Generated by Django 2.2.5 on 2020-01-05 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0015_remove_cartitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='order',
        ),
    ]
