# Generated by Django 2.2.5 on 2020-01-16 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0010_remove_design_guest'),
        ('carts', '0016_remove_cart_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='design',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='designs.Design', verbose_name='デザイン'),
        ),
    ]
