# Generated by Django 2.2.5 on 2020-01-19 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0017_cartitem_design'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='design',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='designs.Design', verbose_name='デザイン'),
        ),
    ]
