# Generated by Django 2.2.5 on 2020-01-24 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feet', '0005_auto_20200124_1037'),
        ('carts', '0020_auto_20200124_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='feet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='feet.Footsize', verbose_name='足サイズ'),
        ),
    ]
