# Generated by Django 2.2.5 on 2020-02-06 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0021_cartitem_feet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='feet',
        ),
    ]
