# Generated by Django 2.2.5 on 2019-11-22 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0002_auto_20191121_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_code',
            field=models.CharField(default='test', max_length=11, verbose_name='レビュー番号'),
        ),
        migrations.AddField(
            model_name='review',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
