# Generated by Django 2.2.5 on 2019-10-23 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20191023_2343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'レビュー', 'verbose_name_plural': 'レビュー'},
        ),
    ]
