# Generated by Django 2.2.5 on 2020-01-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20191203_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_code',
            field=models.CharField(max_length=11, verbose_name='レビュー番号'),
        ),
    ]
