# Generated by Django 2.2.5 on 2019-11-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footsize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
                ('length_left', models.IntegerField()),
                ('length_right', models.IntegerField()),
                ('width_left', models.IntegerField()),
                ('width_right', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
