# Generated by Django 2.2.5 on 2019-12-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feet', '0002_footsize_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footsize',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='footsize',
            name='length_left',
            field=models.IntegerField(verbose_name='足長(左)'),
        ),
        migrations.AlterField(
            model_name='footsize',
            name='length_right',
            field=models.IntegerField(verbose_name='足長(右)'),
        ),
        migrations.AlterField(
            model_name='footsize',
            name='width_left',
            field=models.IntegerField(verbose_name='足幅(左)'),
        ),
        migrations.AlterField(
            model_name='footsize',
            name='width_right',
            field=models.IntegerField(verbose_name='足幅(右)'),
        ),
    ]
