# Generated by Django 2.2.5 on 2020-01-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feet', '0003_auto_20191202_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footsize',
            name='length_left',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='足長(左)'),
        ),
        migrations.AlterField(
            model_name='footsize',
            name='length_right',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='足長(右)'),
        ),
        migrations.AlterField(
            model_name='footsize',
            name='width_left',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='足幅(左)'),
        ),
        migrations.AlterField(
            model_name='footsize',
            name='width_right',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='足幅(右)'),
        ),
    ]
