# Generated by Django 2.2.5 on 2020-01-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feet', '0005_auto_20200124_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='FootImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length_left', models.FileField(upload_to='feet')),
                ('length_right', models.FileField(upload_to='feet')),
                ('width_left', models.FileField(upload_to='feet')),
                ('width_right', models.FileField(upload_to='feet')),
            ],
        ),
    ]
