# Generated by Django 2.2.5 on 2020-01-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feet', '0007_remove_footimage_width_right'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footimage',
            name='length_left',
        ),
        migrations.RemoveField(
            model_name='footimage',
            name='length_right',
        ),
        migrations.RemoveField(
            model_name='footimage',
            name='width_left',
        ),
        migrations.AddField(
            model_name='footimage',
            name='foot_left',
            field=models.ImageField(default=1, upload_to='feet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footimage',
            name='foot_right',
            field=models.ImageField(default=1, upload_to='feet'),
            preserve_default=False,
        ),
    ]
