# Generated by Django 2.2.5 on 2020-01-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feet', '0009_processedfootimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedfootimage',
            name='foot_left',
            field=models.ImageField(blank=True, null=True, upload_to='feet'),
        ),
        migrations.AlterField(
            model_name='processedfootimage',
            name='foot_right',
            field=models.ImageField(blank=True, null=True, upload_to='feet'),
        ),
    ]
