# Generated by Django 2.2.5 on 2020-02-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feet', '0011_auto_20200221_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedfootimage',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
