# Generated by Django 2.2.5 on 2020-02-23 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feet', '0012_processedfootimage_is_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processedfootimage',
            name='is_finished',
        ),
    ]
