# Generated by Django 2.2.5 on 2019-11-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
                ('outsole_color_left', models.CharField(max_length=7, verbose_name='アウトソール色(左)')),
                ('midsole_color_left', models.CharField(max_length=7, verbose_name='ミッドソール色(左)')),
                ('uppersole_color_left', models.CharField(max_length=7, verbose_name='アッパーソール色(左)')),
                ('shoelace_color_left', models.CharField(max_length=7, verbose_name='シューレースホール色(左)')),
                ('tongue_color_left', models.CharField(max_length=7, verbose_name='タン色(左)')),
                ('liner_color_left', models.CharField(max_length=7, verbose_name='ライナー色(左)')),
                ('outsole_color_right', models.CharField(max_length=7, verbose_name='アウトソール色(右)')),
                ('midsole_color_right', models.CharField(max_length=7, verbose_name='ミッドソール色(右)')),
                ('uppersole_color_right', models.CharField(max_length=7, verbose_name='アッパーソール色(右)')),
                ('shoelace_color_right', models.CharField(max_length=7, verbose_name='シューレースホール色(右)')),
                ('tongue_color_right', models.CharField(max_length=7, verbose_name='タン色(右)')),
                ('liner_color_right', models.CharField(max_length=7, verbose_name='ライナー色(右)')),
                ('customize_code', models.CharField(max_length=11, verbose_name='カスタマイズデザインコード')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side_left', models.ImageField(upload_to='', verbose_name='側面(左)')),
                ('side_right', models.ImageField(upload_to='', verbose_name='側面(右)')),
                ('upper_left', models.ImageField(upload_to='', verbose_name='上面(左)')),
                ('upper_right', models.ImageField(upload_to='', verbose_name='上面(右)')),
                ('back_left', models.ImageField(upload_to='', verbose_name='後面(左)')),
                ('back_right', models.ImageField(upload_to='', verbose_name='後面(右)')),
                ('bottom_left', models.ImageField(upload_to='', verbose_name='下面(左)')),
                ('bottom_right', models.ImageField(upload_to='', verbose_name='下面(右)')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='')),
                ('material_code', models.CharField(max_length=2, verbose_name='')),
            ],
        ),
    ]
