# Generated by Django 2.2.5 on 2019-12-02 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0002_auto_20191202_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='design',
            old_name='product_id',
            new_name='product',
        ),
    ]
