# Generated by Django 2.2.5 on 2020-01-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0004_auto_20191211_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='file',
            field=models.FileField(blank=True, upload_to='product_materials', verbose_name='素材画像'),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_code',
            field=models.CharField(max_length=2, verbose_name='素材コード'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=20, verbose_name='素材名'),
        ),
    ]
