# Generated by Django 2.2.5 on 2020-01-14 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0005_auto_20200114_1618'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Material',
        ),
    ]
