# Generated by Django 2.2.5 on 2020-01-14 14:27

import designs.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20200105_2301'),
        ('designs', '0006_delete_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='title',
        ),
        migrations.AddField(
            model_name='design',
            name='design_number',
            field=models.CharField(blank=True, default=designs.models.create_custom_design_code, max_length=40, null=True, verbose_name='番号'),
        ),
        migrations.AddField(
            model_name='design',
            name='guest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design', to='users.Guest'),
        ),
    ]
