# Generated by Django 2.2.5 on 2020-01-15 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0008_auto_20200114_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='design',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='designs.Design', verbose_name='デザインid'),
        ),
    ]
