# Generated by Django 2.2.5 on 2020-01-16 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0009_auto_20200115_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='guest',
        ),
    ]
