# Generated by Django 2.2.5 on 2020-01-17 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0010_remove_design_guest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='素材名')),
                ('file', models.FileField(blank=True, upload_to='product_materials', verbose_name='素材画像')),
                ('material_code', models.CharField(max_length=2, verbose_name='素材コード')),
            ],
        ),
    ]
