# Generated by Django 2.2.5 on 2020-01-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0012_auto_20200117_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='outsole_material_left',
            field=models.ManyToManyField(blank=True, related_name='designs', to='designs.Material'),
        ),
    ]
