# Generated by Django 2.2.5 on 2020-01-17 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0020_auto_20200117_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='liner_material_left',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liner_material_left', to='designs.Material', verbose_name='ライナー素材(左)'),
        ),
        migrations.AddField(
            model_name='design',
            name='liner_material_right',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liner_material_right', to='designs.Material', verbose_name='ライナー素材(右)'),
        ),
        migrations.AddField(
            model_name='design',
            name='midsole_material_right',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='midsole_material_right', to='designs.Material', verbose_name='ミッドソール素材(右)'),
        ),
        migrations.AddField(
            model_name='design',
            name='outsole_material_right',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outsole_material_right', to='designs.Material', verbose_name='アウトソール素材(右)'),
        ),
        migrations.AddField(
            model_name='design',
            name='shoelace_material_left',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shoelace_material_left', to='designs.Material', verbose_name='シューレース素材(左)'),
        ),
        migrations.AddField(
            model_name='design',
            name='shoelace_material_right',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shoelace_material_right', to='designs.Material', verbose_name='シューレース素材(右)'),
        ),
        migrations.AddField(
            model_name='design',
            name='tongue_material_left',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tongue_material_left', to='designs.Material', verbose_name='タン素材(左)'),
        ),
        migrations.AddField(
            model_name='design',
            name='tongue_material_right',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tongue_material_right', to='designs.Material', verbose_name='タン素材(右)'),
        ),
        migrations.AddField(
            model_name='design',
            name='uppersole_material_left',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uppersole_material_left', to='designs.Material', verbose_name='アッパーソール素材(左)'),
        ),
        migrations.AddField(
            model_name='design',
            name='uppersole_material_right',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uppersole_material_right', to='designs.Material', verbose_name='アッパーソール素材(右)'),
        ),
        migrations.AlterField(
            model_name='design',
            name='shoelace_color_left',
            field=models.CharField(max_length=7, verbose_name='シューレース色(左)'),
        ),
        migrations.AlterField(
            model_name='design',
            name='shoelace_color_right',
            field=models.CharField(max_length=7, verbose_name='シューレース色(右)'),
        ),
    ]
