# Generated by Django 2.2.5 on 2020-01-17 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0023_remove_design_liner_material_left'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='liner_color_right',
        ),
        migrations.RemoveField(
            model_name='design',
            name='liner_material_right',
        ),
    ]
