# Generated by Django 2.2.5 on 2020-01-17 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0024_auto_20200117_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='bottom_left',
            new_name='down',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='side_left',
            new_name='front',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='upper_left',
            new_name='side',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='back_left',
            new_name='up',
        ),
        migrations.RemoveField(
            model_name='image',
            name='back_right',
        ),
        migrations.RemoveField(
            model_name='image',
            name='bottom_right',
        ),
        migrations.RemoveField(
            model_name='image',
            name='side_right',
        ),
        migrations.RemoveField(
            model_name='image',
            name='upper_right',
        ),
    ]
