# Generated by Django 2.2.5 on 2020-01-20 09:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('designs', '0026_auto_20200117_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
