# Generated by Django 2.2.5 on 2020-01-24 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0027_design_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignForAnalytics',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('designs.design',),
        ),
    ]
