# Generated by Django 2.2.5 on 2020-01-24 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0028_designforanalytics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DesignForAnalytics',
        ),
    ]
