# Generated by Django 2.2.5 on 2020-01-25 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0029_delete_designforanalytics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='design',
            options={'verbose_name': 'デザイン', 'verbose_name_plural': 'デザイン'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'デザインイメージ', 'verbose_name_plural': 'デザインイメージ'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': '素材', 'verbose_name_plural': '素材'},
        ),
        migrations.AlterField(
            model_name='design',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='いいねユーザ'),
        ),
        migrations.AlterField(
            model_name='design',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design', to='products.Product', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='design',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design', to=settings.AUTH_USER_MODEL, verbose_name='ユーザ'),
        ),
    ]
