# Generated by Django 2.2.5 on 2019-11-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=20, verbose_name='姓')),
                ('first_name', models.CharField(max_length=20, verbose_name='名')),
                ('card_number', models.CharField(max_length=16, verbose_name='カード番号')),
                ('expiration_month', models.CharField(max_length=2, verbose_name='有効期限(月)')),
                ('expiration_year', models.CharField(max_length=2, verbose_name='有効期限(年)')),
            ],
        ),
    ]
