# Generated by Django 2.2.5 on 2019-12-27 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_auto_20191226_2206'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card',
        ),
    ]
