# Generated by Django 2.2.5 on 2019-12-31 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='exp_month',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='exp_year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
