# Generated by Django 2.2.5 on 2019-12-31 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0007_auto_20191231_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='stripe_customer_id',
        ),
        migrations.AddField(
            model_name='card',
            name='stripe_customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='card', to=settings.AUTH_USER_MODEL, verbose_name='ストライプID'),
            preserve_default=False,
        ),
    ]
