# Generated by Django 2.2.5 on 2019-12-31 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_auto_20191231_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='stripe_customer',
        ),
        migrations.AddField(
            model_name='card',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
