# Generated by Django 2.2.5 on 2019-12-13 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=1, verbose_name='登録日時'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name_orderer_kana',
            field=models.CharField(max_length=30, verbose_name='名(カナ)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name_orderer_kana',
            field=models.CharField(max_length=30, verbose_name='姓(カナ)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
    ]
