# Generated by Django 2.2.5 on 2019-12-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20191213_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.AlterField(
            model_name='order',
            name='address_city_orderer',
            field=models.CharField(max_length=40, verbose_name='市区町村(お届け先)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address_city_recipient',
            field=models.CharField(max_length=40, verbose_name='市区町村(ご請求書先)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address_detail_orderer',
            field=models.CharField(max_length=40, verbose_name='建物名・部屋番号(お届け先)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address_detail_recipient',
            field=models.CharField(max_length=40, verbose_name='建物名・部屋番号(ご請求書先)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name_orderer',
            field=models.CharField(max_length=30, verbose_name='名(お届け先)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name_orderer_kana',
            field=models.CharField(max_length=30, verbose_name='名(カナ, お届け先)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name_recipient',
            field=models.CharField(max_length=30, verbose_name='名(ご請求書先)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name_recipient_kana',
            field=models.CharField(max_length=30, verbose_name='名(ご請求書先,カナ)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name_orderer',
            field=models.CharField(max_length=30, verbose_name='姓(お届け先)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name_orderer_kana',
            field=models.CharField(max_length=30, verbose_name='姓(カナ, お届け先)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name_recipient',
            field=models.CharField(max_length=30, verbose_name='姓(ご請求書先)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name_recipient_kana',
            field=models.CharField(max_length=30, verbose_name='姓(ご請求書先,カナ)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number_orderer',
            field=models.CharField(max_length=15, verbose_name='電話番号(お届け先)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number_recipient',
            field=models.CharField(max_length=15, verbose_name='電話番号(ご請求書先)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code_orderer',
            field=models.CharField(max_length=7, verbose_name='郵便番号(お届け先)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code_recipient',
            field=models.CharField(max_length=7, verbose_name='郵便番号(ご請求書先)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='prefecture_orderer',
            field=models.CharField(max_length=2, verbose_name='都道府県(お届け先)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='prefecture_recipient',
            field=models.CharField(max_length=2, verbose_name='都道府県(ご請求書先)'),
        ),
    ]
