# Generated by Django 2.2.5 on 2019-12-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20191222_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('P1', 'クレジットカード'), ('P2', '振込')], max_length=2, verbose_name='支払方法'),
        ),
    ]
