# Generated by Django 2.2.5 on 2019-12-23 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20191218_2144'),
        ('orders', '0007_auto_20191223_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='guest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='users.Guest', verbose_name='ゲスト'),
        ),
    ]
