# Generated by Django 2.2.5 on 2019-12-23 13:16

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number_orderer',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=15, region=None, verbose_name='電話番号(お届け先)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number_recipient',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=15, region=None, verbose_name='電話番号(ご請求書先)'),
        ),
    ]
