# Generated by Django 2.2.5 on 2019-12-25 07:24

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20191223_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_code',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='注文番号'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, default=orders.models.create_order_number, max_length=40, null=True),
        ),
    ]
