# Generated by Django 2.2.5 on 2020-01-05 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0012_auto_20200105_2301'),
        ('orders', '0013_order_step'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-order_date',), 'verbose_name': '注文', 'verbose_name_plural': '注文'},
        ),
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ('step_code',), 'verbose_name': '対応', 'verbose_name_plural': '対応'},
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='carts.Cart', verbose_name='カート'),
        ),
    ]
