# Generated by Django 2.2.5 on 2020-01-06 12:54

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20200105_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='prefecture_orderer',
            field=core.models.JPPrefectureField(max_length=2, verbose_name='都道府県(お届け先)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='prefecture_recipient',
            field=core.models.JPPrefectureField(max_length=2, verbose_name='都道府県(ご請求書先)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.Order', verbose_name='注文アイテム'),
        ),
    ]
