# Generated by Django 2.2.5 on 2020-01-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20200119_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='down',
            field=models.ImageField(default=1, upload_to='orders', verbose_name='下面'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='front',
            field=models.ImageField(default=1, upload_to='orders', verbose_name='正面'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='side',
            field=models.ImageField(default=1, upload_to='orders', verbose_name='側面'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='up',
            field=models.ImageField(default=1, upload_to='orders', verbose_name='上面'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(verbose_name='数量'),
        ),
    ]
