# Generated by Django 2.2.5 on 2020-01-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20200119_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='customize_code',
            field=models.CharField(default=1, max_length=11, verbose_name='カスタマイズデザインコード'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=6, verbose_name='単価'),
        ),
    ]
