# Generated by Django 2.2.5 on 2020-01-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_auto_20200119_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='midsole_color_left',
            field=models.CharField(default=1, max_length=7, verbose_name='ミッドソール色(左)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='midsole_color_right',
            field=models.CharField(default=1, max_length=7, verbose_name='ミッドソール色(右)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='midsole_material_left',
            field=models.CharField(default=1, max_length=7, verbose_name='ミッドソール素材(左)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='midsole_material_right',
            field=models.CharField(default=1, max_length=7, verbose_name='ミッドソール素材(右)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='outsole_color_left',
            field=models.CharField(default=1, max_length=7, verbose_name='アウトソール色(左)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='outsole_color_right',
            field=models.CharField(default=1, max_length=7, verbose_name='アウトソール色(右)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='outsole_material_left',
            field=models.CharField(default=1, max_length=7, verbose_name='アウトソール素材(左)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='outsole_material_right',
            field=models.CharField(default=1, max_length=7, verbose_name='アウトソール素材(右)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shoelace_color_left',
            field=models.CharField(default=1, max_length=7, verbose_name='シューレース色(左)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shoelace_color_right',
            field=models.CharField(default=1, max_length=7, verbose_name='シューレース色(右)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shoelace_material_left',
            field=models.CharField(default=1, max_length=7, verbose_name='シューレース素材(左)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shoelace_material_right',
            field=models.CharField(default=1, max_length=7, verbose_name='シューレース素材(右)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tongue_color_left',
            field=models.CharField(default=1, max_length=7, verbose_name='タン色(左)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tongue_color_right',
            field=models.CharField(default=1, max_length=7, verbose_name='タン色(右)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tongue_material_left',
            field=models.CharField(default=1, max_length=7, verbose_name='タン素材(左)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tongue_material_right',
            field=models.CharField(default=1, max_length=7, verbose_name='タン素材(右)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='uppersole_color_left',
            field=models.CharField(default=1, max_length=7, verbose_name='アッパーソール色(左)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='uppersole_color_right',
            field=models.CharField(default=1, max_length=7, verbose_name='アッパーソール色(右)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='uppersole_material_left',
            field=models.CharField(default=1, max_length=7, verbose_name='アッパーソール素材(左)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='uppersole_material_right',
            field=models.CharField(default=1, max_length=7, verbose_name='アッパーソール素材(右)'),
            preserve_default=False,
        ),
    ]
