# Generated by Django 2.2.5 on 2020-01-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20200120_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='midsole_material_left',
            field=models.CharField(max_length=20, verbose_name='ミッドソール素材(左)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='midsole_material_right',
            field=models.CharField(max_length=20, verbose_name='ミッドソール素材(右)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='outsole_material_left',
            field=models.CharField(max_length=20, verbose_name='アウトソール素材(左)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='outsole_material_right',
            field=models.CharField(max_length=20, verbose_name='アウトソール素材(右)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='shoelace_material_left',
            field=models.CharField(max_length=20, verbose_name='シューレース素材(左)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='shoelace_material_right',
            field=models.CharField(max_length=20, verbose_name='シューレース素材(右)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='tongue_material_left',
            field=models.CharField(max_length=20, verbose_name='タン素材(左)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='tongue_material_right',
            field=models.CharField(max_length=20, verbose_name='タン素材(右)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='uppersole_material_left',
            field=models.CharField(max_length=20, verbose_name='アッパーソール素材(左)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='uppersole_material_right',
            field=models.CharField(max_length=20, verbose_name='アッパーソール素材(右)'),
        ),
    ]
