# Generated by Django 2.2.5 on 2020-01-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_auto_20200121_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='step_code',
            field=models.CharField(max_length=3, verbose_name='対応コード'),
        ),
        migrations.AlterField(
            model_name='step',
            name='step_name',
            field=models.CharField(max_length=20, verbose_name='対応名'),
        ),
    ]
