# Generated by Django 2.2.5 on 2020-02-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_auto_20200206_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='last_name_orderer',
            field=models.CharField(default=1, max_length=30, verbose_name='姓(お届け先)'),
            preserve_default=False,
        ),
    ]
