# Generated by Django 2.2.5 on 2019-10-24 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('code', models.CharField(max_length=5, verbose_name='商品番号')),
                ('name', models.CharField(max_length=50, verbose_name='商品名')),
                ('type', models.CharField(choices=[('H', 'ハイカット'), ('M', 'ミドルカット'), ('L', 'ローカット')], max_length=1, verbose_name='商品種別')),
                ('price', models.IntegerField(default=0, verbose_name='価格')),
                ('description', models.TextField(verbose_name='説明')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('file', models.ImageField(upload_to='product_images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.Product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
