# Generated by Django 2.2.5 on 2019-11-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
                ('product_type', models.CharField(max_length=20, verbose_name='商品タイプ名')),
                ('type_code', models.CharField(max_length=2, verbose_name='タイプコード')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='image',
            old_name='file',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='product',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='code',
            new_name='product_code',
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='販売中'),
        ),
        migrations.AlterField(
            model_name='image',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='登録日時'),
        ),
        migrations.AlterField(
            model_name='image',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='登録日時'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='詳細説明'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時'),
        ),
    ]
