# Generated by Django 2.2.5 on 2019-12-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20191203_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(max_length=7, verbose_name='価格'),
        ),
    ]
