# Generated by Django 2.2.5 on 2019-12-24 14:23

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20191209_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(blank=True, default=products.models.create_product_code, max_length=40, null=True, verbose_name='商品番号'),
        ),
    ]
