# Generated by Django 2.2.5 on 2020-01-14 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20200105_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoelace_left', models.FileField(blank=True, null=True, upload_to='product_templates')),
                ('tongue_left', models.FileField(blank=True, null=True, upload_to='product_templates')),
                ('uppersole_left', models.FileField(blank=True, null=True, upload_to='product_templates')),
                ('midsole_left', models.FileField(blank=True, null=True, upload_to='product_templates')),
                ('outsole_left', models.FileField(blank=True, null=True, upload_to='product_templates')),
                ('shoelace_right', models.FileField(blank=True, null=True, upload_to='product_templates')),
                ('tongue_right', models.FileField(blank=True, null=True, upload_to='product_templates')),
                ('uppersole_right', models.FileField(blank=True, null=True, upload_to='product_templates')),
                ('midsole_right', models.FileField(blank=True, null=True, upload_to='product_templates')),
                ('outsole_right', models.FileField(blank=True, null=True, upload_to='product_templates')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='products.Product', verbose_name='商品')),
            ],
        ),
    ]
