# Generated by Django 2.2.5 on 2020-01-14 03:12

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20200114_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='uppersole_left',
        ),
        migrations.AddField(
            model_name='template',
            name='liner_left',
            field=models.FileField(blank=True, null=True, unique=True, upload_to=products.models.generate_path),
        ),
        migrations.AddField(
            model_name='template',
            name='liner_right',
            field=models.FileField(blank=True, null=True, unique=True, upload_to=products.models.generate_path),
        ),
        migrations.AddField(
            model_name='template',
            name='upper_left',
            field=models.FileField(blank=True, null=True, unique=True, upload_to=products.models.generate_path),
        ),
        migrations.AlterField(
            model_name='template',
            name='midsole_left',
            field=models.FileField(blank=True, null=True, unique=True, upload_to=products.models.generate_path),
        ),
        migrations.AlterField(
            model_name='template',
            name='midsole_right',
            field=models.FileField(blank=True, null=True, unique=True, upload_to=products.models.generate_path),
        ),
        migrations.AlterField(
            model_name='template',
            name='outsole_left',
            field=models.FileField(blank=True, null=True, unique=True, upload_to=products.models.generate_path),
        ),
        migrations.AlterField(
            model_name='template',
            name='outsole_right',
            field=models.FileField(blank=True, null=True, unique=True, upload_to=products.models.generate_path),
        ),
        migrations.AlterField(
            model_name='template',
            name='shoelace_left',
            field=models.FileField(blank=True, null=True, unique=True, upload_to=products.models.generate_path),
        ),
        migrations.AlterField(
            model_name='template',
            name='shoelace_right',
            field=models.FileField(blank=True, null=True, unique=True, upload_to=products.models.generate_path),
        ),
        migrations.AlterField(
            model_name='template',
            name='tongue_left',
            field=models.FileField(blank=True, null=True, unique=True, upload_to=products.models.generate_path),
        ),
        migrations.AlterField(
            model_name='template',
            name='tongue_right',
            field=models.FileField(blank=True, null=True, unique=True, upload_to=products.models.generate_path),
        ),
        migrations.AlterField(
            model_name='template',
            name='uppersole_right',
            field=models.FileField(blank=True, null=True, unique=True, upload_to=products.models.generate_path),
        ),
    ]
