# Generated by Django 2.2.5 on 2020-01-14 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20200114_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='uppersole_right',
            new_name='upper_right',
        ),
    ]
