# Generated by Django 2.2.5 on 2020-01-17 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_material'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Material',
        ),
    ]
