# Generated by Django 2.2.5 on 2020-01-24 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20200119_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='liner_left',
        ),
        migrations.RemoveField(
            model_name='template',
            name='liner_right',
        ),
    ]
